---
config:
  infra:
    aws:
      # account_id: 123456789012
      account_id: 814127428874
      credentials:
        # access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        # secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        # region: ap-southeast-1
      region: ap-southeast-1
      cluster:
        role_name: eks-admin
      instance:
        type: t3.large
        key_pair: ''
        tags:
          managed_by: terraform
        ami_distro: debian
      datalake:
        type: redshift
        key: value
    azure:
      cluster:
      instance:
    gcp:
      cluster:
      instance:
      datalake:
        type: bigquery
        key: value

  platform:
    config:
      image_registry: railsonservices
      images:
        rails:
          static_gems:
            bundler: 2.0.1
            eventmachine: 1.2.7
            ffi: 1.10.0
            mini_portile2: 2.4.0
            msgpack: 1.2.10
            nio4r: 2.3.1
            nokogiri: 1.10.3
            pg: 1.1.4
            puma: 3.12.1
          build_args:
            rails_env: development
            bundle_string: --without production
            os_packages: ['libpq5', 'tree', 'curl', 'git', 'sudo', 'vim', 'less', 'tcpdump', 'net-tools', 'iputils-ping', 'graphviz']
